// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPET3Th4thiOOnz7oKWIyYR1z3Wnop9JE',
    appId: '1:585693738222:web:ec00d843b8abdcf7832fff',
    messagingSenderId: '585693738222',
    projectId: 'my-first-project-975f5',
    authDomain: 'my-first-project-975f5.firebaseapp.com',
    storageBucket: 'my-first-project-975f5.firebasestorage.app',
    measurementId: 'G-DNLNKPQPHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFzSCHjeRLFySxCcqcwYLypto-9LZhnv0',
    appId: '1:585693738222:android:80f0bf67fc43a635832fff',
    messagingSenderId: '585693738222',
    projectId: 'my-first-project-975f5',
    storageBucket: 'my-first-project-975f5.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3QM_b6NyXIJ7s68DE4SJR0nSM-_UemHM',
    appId: '1:585693738222:ios:8cb3d3deab81d613832fff',
    messagingSenderId: '585693738222',
    projectId: 'my-first-project-975f5',
    storageBucket: 'my-first-project-975f5.firebasestorage.app',
    iosBundleId: 'com.example.todolist',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3QM_b6NyXIJ7s68DE4SJR0nSM-_UemHM',
    appId: '1:585693738222:ios:8cb3d3deab81d613832fff',
    messagingSenderId: '585693738222',
    projectId: 'my-first-project-975f5',
    storageBucket: 'my-first-project-975f5.firebasestorage.app',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoVkCte2FV8WRtKkREE08J3Waj9cWbmhQ',
    appId: '1:504196060203:web:424439001138089187466e',
    messagingSenderId: '504196060203',
    projectId: 'to-do-list-8c146',
    authDomain: 'to-do-list-8c146.firebaseapp.com',
    storageBucket: 'to-do-list-8c146.firebasestorage.app',
    measurementId: 'G-7CTP27H6SK',
  );
}
