import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'core/theme/app_theme.dart';
import 'features/auth/bloc/auth_bloc.dart';
import 'features/auth/bloc/auth_event.dart';
import 'features/auth/bloc/auth_state.dart';
import 'features/auth/data/auth_repository.dart';
import 'features/auth/presentation/pages/login_page.dart';
import 'features/notifications/notification_service.dart';
import 'features/tasks/bloc/task_bloc.dart';
import 'features/tasks/bloc/task_event.dart';
import 'features/tasks/data/task_repository.dart';
import 'features/tasks/presentation/pages/home_page.dart';
import 'firebase_options.dart'; // generated by `flutterfire configure`

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  final messengerKey = GlobalKey<ScaffoldMessengerState>();
  // Does nothing on Windows; sets up FCM on Android/iOS.
  await NotificationService(messengerKey).init();

  runApp(MyApp(messengerKey: messengerKey));
}

class MyApp extends StatelessWidget {
  final GlobalKey<ScaffoldMessengerState> messengerKey;
  const MyApp({super.key, required this.messengerKey});

  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (_) => AuthBloc(AuthRepository())..add(AuthCheckRequested()),
      child: MaterialApp(
        debugShowCheckedModeBanner: false,
        title: 'To-Do',
        theme: AppTheme.light,
        scaffoldMessengerKey: messengerKey,
        // The AuthBloc state decides which screen is shown.
        home: BlocBuilder<AuthBloc, AuthState>(
          builder: (context, state) {
            if (state is Authenticated) {
              // One TaskBloc per logged-in user.
              return BlocProvider(
                key: ValueKey(state.userId),
                create: (_) =>
                    TaskBloc(TaskRepository(state.userId))..add(LoadTasks()),
                child: const HomePage(),
              );
            }
            if (state is AuthInitial) {
              return const Scaffold(
                  body: Center(child: CircularProgressIndicator()));
            }
            // Unauthenticated, AuthLoading, AuthError -> login screen
            return const LoginPage();
          },
        ),
      ),
    );
  }
}
